services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8081:8081"
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: /toptal/web
        awslogs-stream: web
        awslogs-create-group: true