services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8082:8082"
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: /toptal/api
        awslogs-stream: api
