name: Deploy to prod

on: 
    workflow_dispatch:

    # push:
    #     branches:
    #         - main

jobs:
    deploy:
      name: Deploy
      runs-on: [ubuntu-slim]
      steps:
        - name: Deploy to prod  
          id: deploy-to-prod
          run: |
            echo ${{ secrets.KEY_GITHUB }} >> /tmp/key
            chmod 600 ~/.ssh/key
            ls -lah ~/.ssh/key
            ssh -i ~/.ssh/key admin@18.215.254.127 cd /home/admin/toptal-project/node-3tier-app2/web && git pull && docker compose restart 
        

